---
title: "NOAA Fatalities and Injuries Per Year & Region"
subtitle: "User Instructions"
author: "inlbk"
date: "April 2017"
output:
  pdf_document: default
---
## Overview of the Application

This Shiny web application displays a bar graph of the number of fatalities and/or injuries due to severe weather events for each of nine climate regions of the contiguous United States during a specified span of years.  The user specifies the requested years via a 2-sided slider, and there are check boxes indicating whether to include fatalities and/or injuries.

The data is taken from the NOAA Severe Weather dataset found at:

https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2

A description of the contents of this file is at:

https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf

## NOAA Database

The NOAA database is cleaned and processed by assigning each of the contigous states to one of nine geographic regions determined by NOAA climate type as seen in https://www.ncdc.noaa.gov/monitoring-references/maps/us-climate-regions.php. 

The regions are as follows:

      - South: AR, KS, LA, MS, OK, TX
      - Ohio Valley: IL, IN, KY, MO, OH, TN, WV
      - Southeast: AL, FL, GA, NC, SC, VA, DC
      - Northeast: CT, DE, ME, MD, MA, NH, NJ, NY, PA, RI, VT
      - Upper Midwest: IA, MI, MN, WI
      - Northern Rockies and Plains: MT, NE, ND, SD, WY
      - Southwest: AZ, CO, NM, UT
      - West: CA, NV
      - Northwest: ID, OR, WA
      
In addition, the year of each event in the dataset is extracted from the BGN_DAT variable, and fatalities and injuries are aggregated by year and geographic region to produce a new dataset that is read in to the Shiny application.

## User Inputs to the Application

The user is asked to specify the starting and ending year for the analysis via a 2-sided slider.  Only severe weather events occuring between and including the two endpoints are counted.  In addition, the user is able to specify, via checkboxes, whether to include fatality data, injury data, or both.

## Output

The app creates a bar graph of the total number of fatalities and/or injuries during the specified years for each geographic region of the continental United States.  

